### ISSUE TITLE
Only waiting for last process of multiple sites

### ISSUE THREAD

**Issue by maxfischer2781** [tardis-resourcemanager/tardis#1]
When using multiple sites, parasites are not properly waited for. Only the last site defined is waited for:

https://github.com/tardis-resourcemanager/tardis/blob/c112c2bb4483502797ce60d54f867cc32a6b5b2e/tardis/__main__.py#L57-L62

**Comment by mschnepf** [comment]
fixed with commit c6c703438de321f7c9a587b120cde389cc261c15
